apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: ClusterIP
  selector:
    app: client
  ports:
  - name: client-service-port
    protocol: TCP
    port: 80
    targetPort: 80