apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - name: mongo-service-port
      protocol: TCP
      port: 27017
      targetPort: 27017