apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-persistent-volume-claim
      containers:
      - name: mongodb
        image: mongo:latest
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "3Gi"
            cpu: "500m"
        command:
          - "mongod"
          - "--bind_ip"
          - "0.0.0.0"
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                key: MONGODB_USERNAME
                name: secrets
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MONGODB_PASSWORD
                name: secrets
        volumeMounts:
          - mountPath: /data/db
            name: mongodb-storage
        ports:
        - containerPort: 27017
          name: mongodb-port