apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: ClusterIP
  selector:
    app: server
  ports:
  - name: server-service-port
    protocol: TCP
    port: 4000
    targetPort: 4000